### ISSUE TITLE
Zed's Crash When Closing and Reopening Cameras

### ISSUE THREAD

**Issue by AlexanderKhazatsky** [stereolabs/zed-sdk#539]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

When I have a list of cameras, if I continue opening and closing them, it eventually fails and my terminal outputs something similar to "can't claim interface 0: -6"

My purpose for doing this is that I want to collect data in a low resolution, but extrinsically calibrate a single camera at a time with high resolution. I only have 3 cameras on at once, and this issue happens frequently.

### Steps to Reproduce

Make a while True loop where you turn cameras on and then off.

### Expected Result

Procedure should be safe to repeat

### Actual Result

Eventually camera's cannot be turned back on again.

### ZED Camera model

ZED2

### Environment

```shell
I am using the most recent SDK, ubuntu 22, and have zed minis and zed 2's.
```

**Comment by AlexanderKhazatsky** [comment]
I wanted to bring attention to this issue again whenever you guys have the chance. The memory leak issue I mentioned in another thread is more blocking than this though :)

**Comment by Myzhar** [comment]
Noted. We are working on this

**Comment by AlexanderKhazatsky** [comment]
Just to check- are you guys able to reproduce the issue?

**Comment by AlexanderKhazatsky** [comment]
Hey! Can you guys please address this.
