### ISSUE TITLE
pyzed.sl.calibration_parameters has no parameter called calibration_parameters

### ISSUE THREAD

**Issue by Bugz-y** [stereolabs/zed-sdk#546]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

 Downloading objects_performance_2.2  100.0%[========================================] 19.7/19.7 MB              Done
 Optimizing objects_performance_2.2 |  100.0%[=============================>] Done ! in 2min 48s
Traceback (most recent call last):
  File "object_detection_image_viewer.py", line 68, in <module>
    viewer.init(camera_info.calibration_parameters.left_cam, obj_param.enable_tracking)
AttributeError: 'pyzed.sl.CameraInformation' object has no attribute 'calibration_parameters'

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

to run 

### Actual Result

it fail running

### ZED Camera model

ZED2

### Environment

```shell
os :windows
python : python11
```

**Comment by alassagne-sl** [comment]
Hi again,

The sample is outdated, I don’t think there is a bug in the wrapper. camera_infos do not contains resolutions anymore.
Can you replace

point_cloud_res = sl.Resolution(min(camera_infos.camera_resolution.width, 720)

with

point_cloud_res = sl.Resolution(min(camera_infos.camera_configuration.resolution.width, 720)
