### ISSUE TITLE
stuck in sl::Camera::retrieveObjects sometime

### ISSUE THREAD

**Issue by PenguiNess** [stereolabs/zed-sdk#548]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

i really appreciate the amazing product you provide us. while using it, i really came up with some issues.  one of them is, while i called function sl::Camera::retrieveObjects to ingest custom bboxes into zed 3d bboxes,  process stucked in this function, and for thread safety, i used zed instance with lock, so when it stucked, other thread cannot acquired lock and cannot use zed instance. so is there anything wrong? do i use is with wrong actions?  and i have set image_sync to false to avoid sync call.

   

### Steps to Reproduce

1.  following is part of my code.
sl::PositionalTrackingParameters zedPositionalTrackingPara;
      zedPositionalTrackingPara.set_as_static = true;
      zedCamInst->enablePositionalTracking(zedPositionalTrackingPara);
      sl::ObjectDetectionParameters obj_param;
      obj_param.image_sync = false;
      obj_param.detection_model = sl::DETECTION_MODEL::CUSTOM_BOX_OBJECTS;
      obj_param.enable_tracking = true;
      zedCamInst->enableObjectDetection(obj_param);

2.   // Retrieve colored point cloud. Point cloud is aligned on the left image.
    auto rm_ret = zed->retrieveMeasure(point_cloud, MEASURE::XYZRGBA);
    // Update pose data (used for projection of the mesh over the current image)
    sl::POSITIONAL_TRACKING_STATE tracking_state = zed->getPosition(cam_w_pose, REFERENCE_FRAME::WORLD);
    sl::CameraParameters calibration_params_left = zed->getCameraInformation().camera_configuration.calibration_parameters.left_cam;
    ......
   
3.  std::vector<sl::CustomBoxObjectData> detections = DetectionsToCustomBox(ai_result_objects);
    zed->ingestCustomBoxObjects(detections);
    auto ro_ret = zed->retrieveObjects(objects, obj_runtime_param);

### Expected Result

process not stucked in this function.

### Actual Result

it stucked .

### ZED Camera model

ZED2i

### Environment

```shell
OS: ubuntu18.04. aarch64 
GPU: NVIDIA Jetson AGX Xavier
CUDA: 10.2.89
cuDNN: 8.0.0.180
TensorRT: 7.1.3.0
OpenCV: 4.1.1 compiled CUDA: YES
ZED version: ZED_SDK_Tegra_L4T32.7_v3.8.2.zstd
```

**Comment by obraun-sl** [comment]
We will try to reproduce. 
Do you have the same behavior with image_sync = true ? 
That will help us to debug
