### ISSUE TITLE
Decrease in depth performance for outdoor conditions when using SDK 4.0, neural depth 2.0

### ISSUE THREAD

**Issue by VGrondin** [stereolabs/zed-sdk#550]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Hi I am a roboticist and employ the ZED camera in a variety of outdoor environments, but mainly forests. After updating to SDK 4.0, I compared the new depth images with the previous one from neural depth 1.0 and noticed a qualitative decrease in depth perception. I read that neural depth 2.0 is supposed to be better in indoor environment mainly for texture-less surfaces, but the difference is quite noticeable. 

### Steps to Reproduce

1.video in forest
2.same depth settings

### Expected Result

Expected better depth estimation, but seems qualitatively significantly worse for outdoor conditions. Might be because neural depth 2.0 it is overtuned for indoor texture-less conditions?

### Actual Result

Quality of depth perception decreased

### ZED Camera model

ZED

### Environment

```shell
OS: Ubuntu
CPU: Ryzen
GPU: 3090
SDK: 4.0
```

### Anything else?

![image_00780_RGB](https://user-images.githubusercontent.com/56001549/230679176-21ec65c2-55ca-4b7c-9c2b-ec737f9eb804.png)
Original RGB image

![image_00780_depth](https://user-images.githubusercontent.com/56001549/230679192-06a1f188-75f2-46b4-b613-4421ed59680a.png)
Neural depth 1.0 (SDK 3.5 i think)

![image_00780_depth](https://user-images.githubusercontent.com/56001549/230679202-8f0286c7-b1ce-466b-a723-ec6259c47361.png)
Neural depth 2.0 (SDK 4.0)

**Comment by P-yver** [comment]
Hi,
The Neural Depth 2.0 is designed to handle noisy images and have a better far accuracy.
It is hard to compare just with images, a 3d point cloud (could be saved as  .ply file with Depth Viewer) could be better.
You can also record a SVO with ZED Explorer and share it with us to be analyzed by our team?
You can share it by email ([support@stereolabs.com](mailto:support@stereolabs.com)) if you prefer to not share it publicly.
