### ISSUE TITLE
zed2i Object Detection Error: INVALID FUNCTION CALL

### ISSUE THREAD

**Issue by jamesheatonrdm** [stereolabs/zed-sdk#554]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

running roslaunch zed_wrapper zed2i.launch with object detection enables gives the error: Object detection error: INVALID FUNCTION CALL.
This repeats continuously as long as the node is running:
[ERROR] [1681727374.816097548]: Object detection error: INVALID FUNCTION CALL
[ INFO] [1681727374.882696006]: *** Starting Object Detection ***
[ERROR] [1681727374.882742133]: Object detection error: INVALID FUNCTION CALL
[ INFO] [1681727374.949369186]: *** Starting Object Detection ***
[ERROR] [1681727374.949422627]: Object detection error: INVALID FUNCTION CALL
[ INFO] [1681727375.016026506]: *** Starting Object Detection ***
[ERROR] [1681727375.016087341]: Object detection error: INVALID FUNCTION CALL

### Steps to Reproduce

1. Install zed-ros-examples
2. Set object_detection.od_enabled to True in zed2i.yaml
3. Launch zed wrapper node
...

### Expected Result

Object detection is performed successfully

### Actual Result

Object detection error: INVALID FUNCTION CALL

### ZED Camera model

ZED2i

### Environment

```shell
Ubuntu 20.04
ROS Noetic
NVIDIA RTX A4000
```

**Comment by Myzhar** [comment]
Cross-post and wrong repository. Closed this and kept open the issue on the ROS Wrapper repository
