### ISSUE TITLE
Outdated tutorials on Body tracking module

### ISSUE THREAD

**Issue by riccardokhm** [stereolabs/zed-sdk#555]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

HI all,
I am testing the new SDK but on trying to run the Body Tracking tutorial on python I continue receiving errors due to missing definition. I am quite sure the data structure is changed with the SDK 4.0 but on the documentation online still it seems unchanged. The class involved is the sl.BodyTrackingParameter(). 

### Steps to Reproduce

1.Run the example.

### Expected Result

I would like to test the python example for body tracking features.

### Actual Result

Here a screenshot from the error I get.
![Untitled](https://user-images.githubusercontent.com/63868396/232781513-aed8814d-2ff9-4fac-b6f1-3439628671b5.png)

### ZED Camera model

ZED2i

### Environment

```shell
OS: Windows 10
SDK: 4.0
Python 3.10
VS 2022 Community
```

**Comment by mattrouss** [comment]
Hi @riccardokhm,

Your Python API package seems not up to date with the ZED SDK 4.0. Have you tried running the `get_python_api.py` located in `C:\Program Files (x86)\ZED SDK\` to install the latest version?
