### ISSUE TITLE
How to use the calibration param ？

### ISSUE THREAD

**Issue by hfdlwt** [stereolabs/zed-sdk#557]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Hi ！ I recalibrated the ZED 2i camera through ros-camera-calibration ， and get the left and right camera internal reference ，but I dont know how to use it to update the camera param 。
Another question ， how to calibrate the ZED 2i  depth image underwater？

### Steps to Reproduce

1. update the camera param
2. calibrate the depth image

### Expected Result

konw the way to use the calibration param 

### Actual Result

I dont know how to do it

### ZED Camera model

ZED2i

### Environment

```shell
CPU : arm
GPU : nx
OS :ubuntu
ZED SDK： JetPack 4.6.X
other: Melodic
```

### Anything else?

no

**Comment by P-yver** [comment]
Hi,
You can take a look at this document to perform your own calibration and use it into the ZED SDK:
https://www.stereolabs.com/docs/opencv/calibration/
