### ISSUE TITLE
incorrect python api documents

### ISSUE THREAD

**Issue by shinel94** [stereolabs/zed-sdk#562]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

https://www.stereolabs.com/docs/video/recording/#video-recording

may be change recording method in v4, in that version may use RecordingParameters ans enable_recording arguments change to RecordingParameters so please update document for use

**Comment by mattrouss** [comment]
Hi @shinel94,

Thank you for the info that's a good catch! We are currently performing an update on our code snippets in our docs, so you can expect to see this fixed soon.
