### ISSUE TITLE
CUDA error when running hello ZED example

### ISSUE THREAD

**Issue by AzeezEbrahim** [stereolabs/zed-sdk#568]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I am encountering the following CUDA error when using the ZED Stereo camera with the ZED SDK:

Any Ideas?

### Steps to Reproduce

1.Run the hello code 
2.
3.
...

### Expected Result

I expect the ZED SDK and CUDA to work seamlessly without encountering any CUDA errors.

### Actual Result

>CUDA error at Camera.cpp:208 code=35(cudaErrorInsufficientDriver) "void __cdecl sl::Camera::close(void)"
>CUDA error at Camera.cpp:236 code=35(cudaErrorInsufficientDriver) "void __cdecl sl::Camera::close(void)"
>CUDA error at Camera.cpp:265 code=35(cudaErrorInsufficientDriver) "void __cdecl sl::Camera::close(void)"
>CUDA error at Camera.cpp:305 code=35(cudaErrorInsufficientDriver) "void __cdecl sl::Camera::close(void)"
>CUDA error at Camera.cpp:310 code=35(cudaErrorInsufficientDriver) "void __cdecl sl::Camera::close(void)"
>CUDA error at Camera.cpp:329 code=35(cudaErrorInsufficientDriver) "void __cdecl sl::Camera::close(void)"

### ZED Camera model

ZED2i

### Environment

```shell
- Camera model: ZED 2i
- OS: Windows 10
- GPU: Nvidia 1050 Ti
- Nvidia Driver Version: 497.09
- ZED SDK: 4.0.3
- CUDA: 12.1
```

### Anything else?

![image](https://github.com/stereolabs/zed-sdk/assets/87777192/e7b4768e-33f4-45c6-a8fc-eb6f5a1ec8e6)

**Comment by Myzhar** [comment]
Hi @AzeezEbrahim 
have you tried to upgrade the NVIDIA driver to the latest version?

**Comment by AzeezEbrahim** [comment]
is there another solution, because i do not want to upgrade the driver, should i downgrade another thing e.g. ZED sdk, CUDA.. etc?

**Comment by AzeezEbrahim** [comment]
**Issue Solved,** 
The Antivirus (Bitdefender), was preventing the camera from working.

**Comment by Minaygt** [comment]
![Screenshot from 2024-07-29 17-28-44](https://github.com/user-attachments/assets/e534f308-7887-4dfc-93e0-6950745af402)

how can i solve this error. Should i install nvidia gpu? but which version?
