### ISSUE TITLE
ZED Mini - USB low bandwidth issue - TX2 - Jetpack 4.6.3

### ISSUE THREAD

**Issue by sriinnovasea** [stereolabs/zed-sdk#569]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I have been experiencing a low USB bandwidth issue when attempting to open ZED_Explorer. Despite attempting various troubleshooting steps such as reconnecting the camera, replacing cable and even replacing it with a new one, none of these approaches have resolved the issue. 

### Steps to Reproduce

**ZED_Diagnostic -c**
**ZED Diagnostic Tool**
- Running ZED SDK Diagnostic : OK  
    **ZED SDK version: 3.8.2**
    CUDA version: V10.2.300
- Running Processor Diagnostic : OK  
    Processor:   ARMv8 Processor rev 3 (v8l)
- Running Graphics Card Diagnostic : OK  
    Graphics card:  NVIDIA Tegra X2
- Running Camera Test Diagnostic : Failed
    Specific resolutions are not available  Replug your device or connect the camera to another USB 3.0 port.
    **Camera: ZED Mini**
    Firmware: 1523
**- Running USB Diagnostic : Failed
    Low USB bandwidth  Read our FAQ to troubleshoot your USB connection issues. (https://support.stereolabs.com/hc/en-us/articles/207635225' style='color: #19b5ec;' >Learn more Frame drops: 70/500 Frame tearing: 0/500**

Diagnostic finished, a file has been generated : ZED_Diagnostic_Results.json

[ZED_Diagnostic_Results.json.txt](https://github.com/stereolabs/zed-sdk/files/11766274/ZED_Diagnostic_Results.json.txt)
<img width="533" alt="Screen Shot 2023-06-16 at 1 22 05 AM" src="https://github.com/stereolabs/zed-sdk/assets/50027247/1cbb6e00-964a-4dce-ad39-db67852dfd0f">

### Expected Result

Camera streaming should work without any issue

### Actual Result

USB bandwidth issue, camera stream fails

### ZED Camera model

ZED Mini

### Environment

```shell
**Jetson TX2 with ConnectTech Carrier Board**
Hardware: **ZED Mini**
OS: **L4T 32.7.3 [ JetPack 4.6.3 ]**
ZED_SDK: **ZED_SDK_Tegra_L4T32.7_v3.8.2.zstd.run**
```

### Anything else?

Nothing

**Comment by Myzhar** [comment]
@sriinnovasea please write an email to support@stereolabs.com and add the report file generated by the ZED_Diagnostic tool.
