### ISSUE TITLE
Problem with high resolution Zed camera

### ISSUE THREAD

**Issue by huyle24022002** [stereolabs/zed-sdk#571]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I use Zed camera and API in C++ to open and capture camera, but i only can open the camera with VGA solution, when i use USB hub to convert my usb gate to 3.0 its sometime can open the camera in higher resolution, is there any tips to fix

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

Can open in higher resolution

### Actual Result

Only open in VGA resolution

### ZED Camera model

ZED

### Environment

```shell
OS: window 11
CPU: AMD ryzen 5 4600H
GPU: GTX 1650ti
SDK: 3.7
```

**Comment by Myzhar** [comment]
Hi @huyle24022002 
Please run the ZED Diagnostic tool and send the report file that it generates to support@stereolabs.com to open support a ticket.
