### ISSUE TITLE
read_fusion_configuration_file is not workking

### ISSUE THREAD

**Issue by nctran108** [stereolabs/zed-sdk#573]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I want to merge two zed2 camera keypoints so I looked at fusion module in zed sdk and I found read_fusion_configuration_file that read configuration file. I created json file with exact format in https://www.stereolabs.com/docs/fusion/overview/. and I also use this https://github.com/stereolabs/zed-sdk/blob/master/body%20tracking/multi-camera/python/fused_cameras.py as my reference. however, when I tried the function I get [json.exception.type_error.302] type must be number, but is null and [json.exception.type_error.302] type must be number, but is null[ZED][ERROR] error when reading the json configuration.
I know that when dumps to json file, all keys convert to string but should read_fusion_configuration_file hae to know how to convert the key back to number?

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

list of zed serial number

### Actual Result

error

### ZED Camera model

ZED2

### Environment

```shell
OS: jetson nano Ubuntu 18.04
```

**Comment by P-yver** [comment]
Hi,
Have you check that your json is valid?
you can use something like this to help you: https://jsonlint.com/
