### ISSUE TITLE
Documentation problem with docker emulation of jetson on x86

### ISSUE THREAD

**Issue by jabowery** [stereolabs/zed-sdk#576]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

The documentation at URL:

https://www.stereolabs.com/docs/docker/building-arm-container-on-x86/

should have the command:

`docker run --platform=linux/arm64/v8 --rm -t arm64v8/ubuntu uname -m`

rather than the command:

`docker run --rm -t arm64v8/ubuntu uname -m `

### Steps to Reproduce

1. Follow the instructions up to:
2. `docker run --rm -t arm64v8/ubuntu uname -m` 

### Expected Result

```
docker run --rm -t arm64v8/ubuntu uname -m # Testing the emulation environment
#aarch64
```

### Actual Result

```
docker run --rm -t arm64v8/ubuntu uname -m 
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
aarch64
```

### ZED Camera model

ZED

### Environment

```shell
OS: Ubuntu
```

### Anything else?

Not using your camera.  Just the howto linked above.

**Comment by Myzhar** [comment]
Hi @jabowery 
thank you for reporting. We noted it and the documentation will be fixed as soon as possible.
