### ISSUE TITLE
ROI seems to have no effect on exposure digital-gain and analog-gain settings

### ISSUE THREAD

**Issue by DerekvdVen** [stereolabs/zed-sdk#590]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

For our application we want to set the sl.VIDEO_SETTINGS.AEC_AGC_ROI to only the bottom half of the image. While experimenting with setting the ROI I found that when setting it to a corner of the image, the exposure and gain still change a lot when darkening non ROI parts of the image. Only the digital gain seems to start changing when the box is covered but that's just because the image becomes so dark. Either I'm doing something wrong, or the ROI seems to have no effect. 

Image without dark object (exp32999, analog gain: 1085, digital gain: 1:
![im_18_exp32999_ag1085_dg1](https://github.com/stereolabs/zed-sdk/assets/33826759/f23b4173-5953-46b8-984a-6e37cf1db94b)

Image with dark object not in ROI (exp32999, analog gain: 10516, digital gain: 1)
![im_122_exp32999_ag10516_dg1](https://github.com/stereolabs/zed-sdk/assets/33826759/d3d72402-41fa-4659-9dc9-36e24c2e6fcc)

Image with dark object in entire image (exp32999, analog gain: 16000, digital gain: 111)
![im_150_exp32999_ag16000_dg111](https://github.com/stereolabs/zed-sdk/assets/33826759/9d44da99-b02e-46d0-8078-5528257687ac)

My code:
[take_images.txt](https://github.com/stereolabs/zed-sdk/files/12610178/take_images.txt)

### Steps to Reproduce

Take my code and run it. Hold a black object in front of the image and see the values change. 

### Expected Result

I would expect the exposure gain only to change when a significant lighting effect takes place inside the ROI. 

### Actual Result

The exposure and gain still change based on the entire image as roi. 

### ZED Camera model

ZED

### Environment

```shell
OS: Ubuntu Jetson Orin AGX
CPU: arm64
GPU: Ampere GPU and a 6-core ARM CPU
ZED SDK version: 4.0.6
Other: It's not the ZED camera, it's the ZED X MINI (not in the list)
```

### Anything else?

It's not the ZED camera, it's the ZED X MINI (not in the list)

**Comment by DerekvdVen** [comment]
I suspect it may have to do with our rotating the camera, am looking into this.

**Comment by DerekvdVen** [comment]
I did make a mistake with the camera, but when setting the ROI correctly, the results still look a bit strange. It still responds more to bright parts outside the ROI than pixel values inside it.

**Comment by P-yver** [comment]
Hi,
I will have a look at this but it may be due to the fact that the ROI is too small.

**Comment by DerekvdVen** [comment]
Hi,

Thanks for taking a look. 

The code I sent you at first has a mistake in it, but after fixing we still face the situation same situation. 

We set the ROI to the bottom half of the image. Then, when we cover the top half with a black screen, we still see significant lighting changes in the bottom. Maybe this is expected because less light is entering the bottom half? But I would expect that the pixel values in the lower half don't really change and we would not get such a significant increase in lighting. 

![image](https://github.com/stereolabs/zed-sdk/assets/33826759/a0c20cc5-a393-44b3-a0b5-c7ac1408ba93)
