### ISSUE TITLE
Positional and Spatial Mapping Python

### ISSUE THREAD

**Issue by pfcouto** [stereolabs/zed-sdk#595]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

Is there any tutorial or example, or has anyone already done a project in python capable of doing exactly what is in the SLAM video of the zed2i stereolabs page? Thanks!

https://cdn2.stereolabs.com/assets/video/zed-spatial-mapping-point-cloud.mp4

### Use-Case

Positional and Spatial Mapping in python to do a slam. Not just a mesh

**Comment by Myzhar** [comment]
Please refer to the Spatial Mapping examples in this repository:
https://github.com/stereolabs/zed-sdk/tree/master/spatial%20mapping
