### ISSUE TITLE
Multi Spatial Mapping

### ISSUE THREAD

**Issue by celikemir** [stereolabs/zed-sdk#597]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Spatial mapping works well, but when attempting to use two Zed cameras together, it only shows a black reconstructed point cloud. I have obtained the calibration .json files from Zed360. I also have a question: If I rigidly mount these two cameras on a stick and obtain the correct calibration matrix from Zed360, can I move the stick and still achieve accurate results with spatial mapping?

### Steps to Reproduce

1. cd /usr/local/zed/samples/spatial mapping/multi camera/cpp/ && mkdir build && cd build && cmake .. && make 
2. ./ZED_SpatialMappingFusion zed_calibration_360.json

### Expected Result

I expect colored mesh and nice reconstructed point cloud.

### Actual Result

![Screenshot from 2023-11-07 21-00-04](https://github.com/stereolabs/zed-sdk/assets/33879396/801916d5-1a19-4bdd-b51b-29ea73e6c840)

### ZED Camera model

ZED2i

### Environment

```shell
OS: Ubuntu 20.04
CPU x64
GPU Nvidia Jetson Nx
Zed SDK 4.0
```

**Comment by SLJLMacarit** [comment]
Hi, I'll paste here what I said on the forum as we missed this issue:

For now, it’s not possible to save the textures when using the spatial mapping fusion, it’s only possible in mono-camera. Thanks for the feedback, it’s something we want to do but it probably won’t be short-term.

On the other side, yeah you can use the multi-recording sample to record SVO, but you will also need the ZED360 configuration file for the camera to run the spatial mapping fusion sample with the SVOs.

Explanations on how to modify the ZED360 configuration file for SVO can be found in this post : [Fusion Sample Code with SVO Files - #2 by JPlou](https://community.stereolabs.com/t/fusion-sample-code-with-svo-files/2391/2)
