### ISSUE TITLE
CMake of Download

### ISSUE THREAD

**Issue by bobdavies2000** [stereolabs/zed-sdk#604]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

CMake of the download fails - missing SL_Hub?  I am upgrading to the CUDA 12.1 with SL 4.08 Github repository (the latest available.)  I am running CMake-Gui.  Below is the log of what CMake reports.  This sounds like a simple error on my part but I am unable to see what I did wrong.  I upgraded to the latest CMake 3.28 in trying to fix this.

Bob Davies

Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
The C compiler identification is MSVC 19.36.32537.0
The CXX compiler identification is MSVC 19.36.32537.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
CMake Warning (dev) at body tracking/body tracking/cpp/CMakeLists.txt:14 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at body tracking/export/fbx export/cpp/CMakeLists.txt:16 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at body tracking/export/fbx export/cpp/CMakeLists.txt:33 (message):
  FBX library not found
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at body tracking/multi-camera/cpp/CMakeLists.txt:15 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.1 (found version "12.1") 
CMake Warning (dev) at camera control/cpp/CMakeLists.txt:16 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.1 (found suitable version "12.1", minimum required is "12") 
CMake Warning (dev) at camera streaming/receiver/cpp/CMakeLists.txt:16 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at camera streaming/sender/cpp/CMakeLists.txt:15 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at depth sensing/depth sensing/cpp/CMakeLists.txt:15 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at depth sensing/multi camera/cpp/CMakeLists.txt:20 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at depth sensing/image refocus/cpp/CMakeLists.txt:15 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:25 (add_subdirectory):
  add_subdirectory given source "depth sensing/region of interest/cpp" which
  is not an existing directory.

CMake Warning (dev) at geotracking/live geotracking/cpp/CMakeLists.txt:9 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

Could NOT find GPS (missing: GPS_INCLUDE_DIR GPS_LIBRARY) 
GPSD was not FOUND. the sample will not be able to read live GNSS data
CMake Warning at geotracking/live geotracking/cpp/CMakeLists.txt:27 (find_package):
  By not providing "FindSL_HUB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SL_HUB", but
  CMake did not find one.

  Could not find a package configuration file provided by "SL_HUB" with any
  of the following names:

    SL_HUBConfig.cmake
    sl_hub-config.cmake

  Add the installation prefix of "SL_HUB" to CMAKE_PREFIX_PATH or set
  "SL_HUB_DIR" to a directory containing one of the above files.  If "SL_HUB"
  provides a separate development package or SDK, be sure it has been
  installed.

CMake Warning (dev) at geotracking/playback/cpp/CMakeLists.txt:9 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at geotracking/playback/cpp/CMakeLists.txt:17 (find_package):
  By not providing "FindSL_HUB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SL_HUB", but
  CMake did not find one.

  Could not find a package configuration file provided by "SL_HUB" with any
  of the following names:

    SL_HUBConfig.cmake
    sl_hub-config.cmake

  Add the installation prefix of "SL_HUB" to CMAKE_PREFIX_PATH or set
  "SL_HUB_DIR" to a directory containing one of the above files.  If "SL_HUB"
  provides a separate development package or SDK, be sure it has been
  installed.

CMake Warning (dev) at geotracking/recording/cpp/CMakeLists.txt:10 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.1 (found version "12.1") 
Could NOT find GPS (missing: GPS_INCLUDE_DIR GPS_LIBRARY) 
GPSD was not FOUND ... the resulted sample will not be able to read live GNSS data
CMake Warning (dev) at object detection/image viewer/cpp/CMakeLists.txt:15 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.1 (found suitable version "12.1", minimum required is "12") 
CMake Warning (dev) at object detection/birds eye viewer/cpp/CMakeLists.txt:15 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at object detection/concurrent detections/cpp/CMakeLists.txt:15 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at plane detection/plane detection/cpp/CMakeLists.txt:15 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at plane detection/floor plane/cpp/CMakeLists.txt:15 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at positional tracking/positional tracking/cpp/CMakeLists.txt:15 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at spatial mapping/spatial mapping/cpp/CMakeLists.txt:15 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at recording/export/sensors/cpp/CMakeLists.txt:6 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at recording/export/svo/cpp/CMakeLists.txt:16 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:38 (add_subdirectory):
  add_subdirectory given source "recording/playback/cpp" which is not an
  existing directory.

CMake Warning (dev) at recording/recording/multi camera/cpp/CMakeLists.txt:19 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at recording/recording/mono/cpp/CMakeLists.txt:16 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at tutorials/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Warning (dev) at tutorials/tutorial 1 - hello ZED/cpp/CMakeLists.txt:14 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at tutorials/tutorial 2 - image capture/cpp/CMakeLists.txt:14 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at tutorials/tutorial 3 - depth sensing/cpp/CMakeLists.txt:14 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at tutorials/tutorial 4 - positional tracking/cpp/CMakeLists.txt:14 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at tutorials/tutorial 5 - spatial mapping/cpp/CMakeLists.txt:14 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at tutorials/tutorial 6 - object detection/cpp/CMakeLists.txt:14 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at tutorials/tutorial 7 - sensor data/cpp/CMakeLists.txt:14 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at tutorials/tutorial 8 - body tracking/cpp/CMakeLists.txt:14 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

Configuring incomplete, errors occurred!

### Steps to Reproduce

Just download the Github repo https://github.com/stereolabs/zed-sdk and run CMake-Gui to prepare it.

### Expected Result

I was hoping to build all the samples.

### Actual Result

Nothing is able to be built if CMake is failing.

### ZED Camera model

ZED2i

### Environment

```shell
Windows 11 Pro build 22621
CUDA 12.1
Zed-SDK 4.08
CMake 3.28
```

### Anything else?

I was able to build the tutorials fine.

**Comment by martinkorob** [comment]
Hey Bob any chance you resolved this? Seems like the Cmake list is old. I've tried editting it but can't seem to get it fully resolved.

**Comment by bobdavies2000** [comment]
Martin - I just tested it again and it is still failing for me.  And that
is with CUDA 12.3 and the latest ZED SDK.  I would still like to get these
examples so please post if you find a solution.

Bob Davies

**Comment by martinkorob** [comment]
I ended up using the file below because I really only wanted to run through the tutorials. Lemme know if that works for you.

[CMakeLists.txt](https://github.com/user-attachments/files/18301162/CMakeLists.txt)

**Comment by martinkorob** [comment]
Note this is for C#
