### ISSUE TITLE
ZED360 - Multi Camera Calibration API Reference

### ISSUE THREAD

**Issue by buvur** [stereolabs/zed-sdk#608]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Preface
I am currently working on a multiple camera setup for human body tracking. The provided interface tool _ZED360_ offers the possibilty to easily calibrate the cameras by using an iterative optimization method to align the human sekeleton over an intervall of approx. 10 seconds. The calibration file includes various rotation and translation parameters, where one camera is being selected as the origin. The position of the remaining camera are then estimated relatively to the origin camera.

**Goal:** The idea is to use the Fusion API and its modules to recreate this tool by e.g. using ```FusionConfiguration``` struct and ```write_configuration_file``` to create a calibration file.

 ### Proposal

```pefromMultiCameraCalibration()```- Method that allows to calibrate various cameras on the fly and overwrite the parameters of an exisiting calibration file. It is also imaginable to set an threshold value to exit the calibration process.

**Comment by Myzhar** [comment]
Please use the official customer support channels: [support@stereolabs.com](mailto:support@stereolabs.com) or https://community.stereolabs.com/

GitHub issues should be used to report problems of the repository they refer to.
