### ISSUE TITLE
Depth_Viewer does not plot images

### ISSUE THREAD

**Issue by Sepirence** [stereolabs/zed-sdk#609]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I have trouble to use Depth Viewer with my ZED Mini
Actually, Depth Viewer GUI does not work.

### Steps to Reproduce

I downloaded latest SDK, passes all ZED Diagnostic, and there is no problem when I using ZED_Explorer.
However I got problem with Depth Viewer.

### Expected Result

There is no problem with connection, program get s/n number and no halt when I try to change resolution.

### Actual Result

I could not get and gui from Depth Viewer image as
![Screenshot from 2024-01-12 17-06-30](https://github.com/stereolabs/zed-sdk/assets/28651871/68f51783-d3c6-4e2e-a063-2144595ad2f1)

Weird thing is when I try to save capture on settings, I can get clear images. 

### ZED Camera model

ZED Mini

### Environment

```shell
OS: Linux Ubuntu 20.04
CPU: i9-10870XE
GPU Nvidia RTX3090Ti
SDK version: 4.0.8
CUDA: 11.8
Nvidia Driver : 525.140
```

### Anything else?

Only I received warning message from ZED Diagnostic while checking ZED SDK, and the other tests are all passed.
cmd line:
```
ZED Diagnostic Tool

- Running ZED SDK Diagnostic : OK  
    ZED SDK version: 4.0.8
    CUDA version: V11.8.89
- Running Processor Diagnostic : OK  
    Processor:   Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz
    Motherboard:  WS X299 SAGE, ASUSTeK COMPUTER INC.
- Running Graphics Card Diagnostic : OK  
    Graphics card:  NVIDIA GeForce RTX 3090 Ti
    Graphics card:  NVIDIA GeForce RTX 3090 Ti
- Running Devices Diagnostic : OK  
- Running Camera Test Diagnostic : OK  
    Camera: ZED Mini
    Firmware: 1523
```
warning:
```
/usr/local/zed/tools$ ZED_Diagnostic 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by Myzhar** [comment]
Please use the official customer support channels: [support@stereolabs.com](mailto:support@stereolabs.com) or https://community.stereolabs.com/

GitHub issues should be used to report problems of the repository they refer to.
