### ISSUE TITLE
sl::InitParameters::enable_image_validity_check not saved/loaded from yaml file

### ISSUE THREAD

**Issue by feendres** [stereolabs/zed-sdk#612]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I set my `sl::InitParameters` to
 ```init_parameters_.depth_mode = sl::DEPTH_MODE::NEURAL;         
    init_parameters_.coordinate_units = sl::UNIT::MILLIMETER;    
    init_parameters_.camera_resolution = sl::RESOLUTION::HD1080; 
    init_parameters_.enable_image_validity_check = true;
    init_parameters_.depth_stabilization = 0;
    init_parameters_.camera_fps = 15;
    init_parameters_.depth_minimum_distance = 300;
    init_parameters_.depth_maximum_distance = 3000;
```

and save with `sl::InitParameters::save(sl::String filename)`

The resulting yaml file looked like 
 ```%YAML:1.0
InitParameters:
   camera_resolution: "1"
   camera_fps: "15"
   sdk_verbose_log_file: ""
   svo_real_time_mode: "0"
   coordinate_units: "0"
   coordinate_system: "0"
   depth_mode: "4"
   depth_minimum_distance: "300.000000"
   depth_maximum_distance: "3000.000000"
   camera_image_flip: "2"
   enable_right_side_measure: "0"
   camera_disable_self_calib: "0"
   sdk_verbose: "0"
   sdk_gpu_id: "-1"
   depth_stabilization: "0"
   input_type_input: "6"
   input_type_conf: "0"
   optional_settings_path: ""
   sensors_required: "0"
   enable_image_enhancement: "1"
   optional_opencv_calibration_file: ""
   open_timeout_sec: "5.000000"
```

So it doesn't mention enable_image_validity_check.

When i added it to the yaml file with
`enable_image_validity_check: "1"`  and loaded it with `sl::InitParameters::load(sl::String filename)`
and checked `init_parameters_.enable_image_validity_check` at runtime it was still zero.

Kind Regards
Felix

### Steps to Reproduce

1. Set enable_image_validity_check = true;
2. Save InitParameters to yaml file
3. Load InitParameters from yaml file
4. Check enable_image_validity_check

### Expected Result

enable_image_validity_check Parameter should be saved to yaml file and loaded from yaml file.

### Actual Result

enable_image_validity_check Parameter is not saved to yaml file and can't be loaded from yaml file.

### ZED Camera model

ZED2i

### Environment

```shell
OS: Ubunt20.04
SDK Version: 4.08
```

**Comment by Myzhar** [comment]
@feendres Thank you for reporting this problem.

Please note that this is a bug of the ZED SDK, not of the ZED examples/tutorials that are available in this repository.
If you notice other SDK bugs please send an email to support@stereolabs.com as recommended:

![image](https://github.com/stereolabs/zed-sdk/assets/3648617/97bb77e9-4cc2-4030-9f85-90642ca15d85)
