### ISSUE TITLE
BODY_FORMAT.BODY_70

### ISSUE THREAD

**Issue by katsunori-waragai** [stereolabs/zed-sdk#621]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

## selection of `sl.BODY_FORMAT`
I am happy to have more BODY_FORMAT models to choose from in `zed-sdk/body tracking/body tracking/python$ python body_tracking.py`.
`body_param.body_format = sl.BODY_FORMAT.BODY_38`
worked.
But unfortunately
`body_param.body_format = sl.BODY_FORMAT.BODY_70`
did not work.

I have confirmed that the version of pyzed is 4.0.8.

### Steps to Reproduce

1.   `git clone git@github.com:stereolabs/zed-sdk.git`
2.   `cd "zed-sdk/body tracking/body tracking/python"`
3. edit body_trackng.py

```
-    body_param.body_format = sl.BODY_FORMAT.BODY_18  # Choose the BODY_FORMAT you wish to use
+    body_param.body_format = sl.BODY_FORMAT.BODY_70  # Choose the BODY_FORMAT you wish to use
```

4. python body_trackng.py

### Expected Result

`python body_trackng.py`
runs.
and with 4 key points per finger.
`BODY_70: New body model with hand and finger tracking, with 4 key points per finger.`

### Actual Result

However  failed.
```
Traceback (most recent call last):
  File "body_tracking.py", line 164, in <module>
    main() 
  File "body_tracking.py", line 102, in main
    body_param.body_format = sl.BODY_FORMAT.BODY_70  # Choose the BODY_FORMAT you wish to use
  File "/usr/lib/python3.8/enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: BODY_70
```

### ZED Camera model

ZED2i

### Environment

```shell
OS: Ubuntu20 
CPU: ARM
GPU: Nvidia Jetson AGX Orin
ZED SDK version: 4.0.8
```

**Comment by mattrouss** [comment]
Hi @katsunori-waragai,

The body format BODY_FORMAT.BODY_70 has been removed from the ZED SDK, and is not currently planned to be released.
