### ISSUE TITLE
DEPTH_NEURAL often gives missing disparity for not so near objects

### ISSUE THREAD

**Issue by katsunori-waragai** [stereolabs/zed-sdk#625]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

`DEPTH_MODE.NEURAL` is expected to calculate disparity based on deep learning.
Therefore, I acquired disparity while changing the combination of the following parameters.
```
init_params.camera_resolution
init_params.depth_mode
```

- As a result, I realized that the disparity of objects around 60cm and nearer may not be calculated when `init_params.depth_mode = sl.DEPTH_MODE.NEURAL.`

### Steps to Reproduce

1. Prepare a script to save to save disparity data and depth_image using `sl.DEPTH_MODE.ULTRA`
 and using

```
        zed.retrieve_measure(disparity, sl.MEASURE.DISPARITY)
        disparity_img = disparity.get_data()
        zed.retrieve_image(depth_image, sl.VIEW.DEPTH)
        depth_image_img = depth_image.get_data()
```
2. Check if the object around 60 cm gives proper disparity. The disparity is_finite().
3. Modified the script to use `sl.DEPTH_MODE.NEURAL`
4. Check if the object around 60 cm gives proper disparity. The disparity is_finite().

### Expected Result

disparity of the object at 60 cm  should return finite disparity.
![disparity_0002](https://github.com/stereolabs/zed-sdk/assets/149886409/ade0719b-5772-40c0-a4aa-b89336cd59bf)

### Actual Result

disparity of the object at 60 cm is `isneginf`.

It doesn't happen all the time, but it happens quite often.
![disparity_0001](https://github.com/stereolabs/zed-sdk/assets/149886409/9eaf3a85-b735-4292-a0e3-ae8389a3e1b6)

### ZED Camera model

ZED2i

### Environment

```shell
OS: Ubuntu20 
CPU: ARM
GPU: Nvidia Jetson AGX Orin
ZED SDK version: 4.0.8
```

**Comment by mattrouss** [comment]
Depth values with low confidence are filtered out of the depth map, which allows to retrieve only depth values that the ZED SDK is confident with.

As the confidence values are computed differently between QUALITY and NEURAL depth modes, this would explain the differences you describe here.

You can control the confidence threshold using the runtime parameter: [RuntimeParameters.confidence_threshold](https://www.stereolabs.com/docs/api/structsl_1_1RuntimeParameters.html#ade2446d6529e8416f2f8ae002eaeb149)

Setting this parameter to 100 for NEURAL mode will produce a full depth map without any infinite values.
