### ISSUE TITLE
The best way to operate and record synchronized  left, right streams without ZED sdk 

### ISSUE THREAD

**Issue by sunwell1994** [stereolabs/zed-sdk#640]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

My machine does not have the GPU. I want to just record synchronized  left, right streams with my customized control in Python. 
As https://www.stereolabs.com/docs/installation/specifications noted, "The ZED camera is UVC (Universal Video Class) compliant so you can capture the left and right video streams of the ZED on any Windows and Linux platforms." Is it implied that we can record video streams with Opencv directly, similar to how we access a common camera? 
How can we guarantee the synchronization?

**Comment by obraun-sl** [comment]
The output of the ZED camera without the ZED SDK is already a Side by Side image that contains left and right images synchronized.
Direct capture with opencv will give you this image. You just have to crop the SBS into Left and Right to get both image in separated Mat.
