### ISSUE TITLE
Incorrect swap in Custom Object Detector example?

### ISSUE THREAD

**Issue by mluogh** [stereolabs/zed-sdk#645]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

There is [this line](https://github.com/stereolabs/zed-sdk/blob/229593e845c26fc13e5054c332309a3bd7be1af7/object%20detection/custom%20detector/python/pytorch_yolov8/detector.py#L75) in the example for custom detector that converts the color space before sending it to Yolov8.

`img = cv2.cvtColor(image_net, cv2.COLOR_BGRA2RGB)`

But the [Yolo docs](https://docs.ultralytics.com/modes/predict/#inference-sources) say that it actually expects BGR when it comes from an np.ndarray data source.

![image](https://github.com/user-attachments/assets/d223f688-187e-4928-8ecd-00af91ed8016)

### Steps to Reproduce

1. Inspect the code.

### Expected Result

I expect that we use the correct color space for model accuracy.

### Actual Result

I suspect that we are using the wrong color space.

### ZED Camera model

ZED

### Environment

```shell
Orin Nano.
```

**Comment by umanema** [comment]
This is still not fixed. I've encountered the same issue and was wondering why YOLO behaves differently when I run it from your examples and figured our that color space conversion is wrong
