### ISSUE TITLE
ZED SDK Download Link Broken

### ISSUE THREAD

**Issue by alberthli** [stereolabs/zed-sdk#646]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

The links to download ZED SDKs seem to be broken.

### Steps to Reproduce

Go to the [website](https://www.stereolabs.com/developers/release) and attempt to download any SDK. For instance, going to the link [https://download.stereolabs.com/zedsdk/4.1/cu121/ubuntu22](https://download.stereolabs.com/zedsdk/4.1/cu121/ubuntu22) gives an "Unable to Connect" error for me (I'm using FireFox).

### Expected Result

I should be able to download the SDK.

### Actual Result

I can't.

### ZED Camera model

ZED

### Environment

```shell
N/A
```

**Comment by sumo43** [comment]
I'm not able to download it either. Please fix!

**Comment by jerrytamchiho** [comment]
Still unable to download it... its November
