### ISSUE TITLE
Does the ZED-Mini camera only work on devices with discrete graphics cards?

### ISSUE THREAD

**Issue by yanzhang920817** [stereolabs/zed-sdk#657]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Hello, we purchased a ZED-m camera, and it works fine when we install Ubuntu 20.04 on an i5 PC. However, we installed Ubuntu 20.04 on an i5 IPC, and we can only see the video stream with a low probability using cheese, but we can't see it with a high probability. The i5 IPC doesn't have a GPU, and we don't need the SDK of ZED-m yet, so we don't install the SDK on the i5 IPC, and just use it as a normal camera. What kind of software or hardware is missing that will cause this problem? The i5 PC has an independent graphics card, and the i5 IPC has an integrated graphics card.

### Steps to Reproduce

1. Install Ubuntu 20.04 on an i5 integrated graphics device;
2. Insert the ZED-Mini camera;
3. Open Cheese and you cannot use the ZED-Mini camera

### Expected Result

1. Install Ubuntu 20.04 on an i5 integrated graphics device;
2. Insert the ZED-Mini camera;
3. Open Cheese to use the ZED-Mini camera

### Actual Result

Open Cheese and you cannot use the ZED-Mini camera

### ZED Camera model

ZED

### Environment

```shell
OS:ubuntu 20.04
CPU:i5
GPU:none
```

**Comment by Myzhar** [comment]
A compatible NVIDIA GPU is a mandatory requirement to execute ZED SDK based software
