### ISSUE TITLE
Which algorithm is used in positional tracking example ??how??

### ISSUE THREAD

**Issue by Natene** [stereolabs/zed-sdk#661]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

we want use the track algorithm ,but the camera can not be used again in the same time

**Comment by Myzhar** [comment]
Please post questions to the Stereolabs Community Forum.
GitHub issues are only for Bug Reports and real Feature Requests
